[package]
name = "waveshare-display"
version = "0.1.0"
authors = ["Rahix <rahix@rahix.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.4"
