[package]
authors = ["Rahix <rahix@rahix.de>"]
edition = "2018"
readme = "README.md"
name = "pavu-mixer-firmware"
version = "0.0.0"
publish = false
autobins = false

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.13"
micromath = "1.1.1"
panic-rtt-target = { version = "0.1.1", features = ["cortex-m"] }
postcard = "0.6.1"
rtt-target = { version = "0.3.0", features = ["cortex-m"] }
stm32f3xx-hal = { version = "0.6.1", features = ["stm32f303xc", "stm32-usbd"] }
usb-device = "0.2.8"
usbd-serial = "0.1.1"
waveshare-display = { path = "../waveshare-display/" }
common = { path = "../common/", package = "pavu-mixer-common" }
embedded-hal = "0.2.4"

[[bin]]
name = "pavu-mixer-firmware"
test = false
bench = false

[profile.dev]
opt-level = "s"
lto = true

[profile.release]
codegen-units = 1
debug = true
lto = true
